### ISSUE TITLE
Measured Geometry Problem with geolatte-1.1

### ISSUE THREAD

**Issue by MartinSteinwender** [GeoLatte/geolatte-geom#56]
Hi,

I ran into problems storing measured jts-geometries 
where M-Ordinates where not set
I could make it work with some minor changes

fist Problem was in org.geolatte.geom.jts.JTS.from(Geometry)
(called in JTSGeometryJavaTypeDescriptor.unwrap)

second Problem was in org.geolatte.geom.jts.PointSequenceCoordinateSequenceFactory.toPositionSequence(...)
(is call on org.geolatte.geom.jts.JTS.pscsFactory)

I had also Problems with 
com.vividsolutions.jts.geom.impl.CoordinateArraySequence.getOrdinate(int, int)
since this methode does not support m-Values.
I would like it to not restrict the ordinateIndex, e.g.:

  @Override
  public double getOrdinate(int index, int ordinateIndex) {
    return coordinates[index].getOrdinate(ordinateIndex);
  }

with these changes persisting MGeometries works for me (tagged with "Modification" )
I hope this ist usefull for the project

[changed.zip](https://github.com/GeoLatte/geolatte-geom/files/1380516/changed.zip)

added check for the MValues not lost to test_measured_2d and test_measured_3d
[TestJTS.zip](https://github.com/GeoLatte/geolatte-geom/files/1380722/TestJTS.zip)

**Comment by maesenka** [comment]
Could you elaborate on what the problems were that you ran into? 

I didn't support writing M-values to (or testing for M-values in) JTS-geometries because JTS doesn't really support measures.  So I'm curious what your use case is?

Anyway, I'll consider your contribution. But you really should be using a Pull Request to contribute to a project on GitHub.

**Comment by maesenka** [comment]
This is now merged into master
