### ISSUE TITLE
dose this support geojson draft version 5 ?

### ISSUE THREAD

**Issue by billtian** [GeoLatte/geolatte-geom#81]
Dose this library support [geojson draft version 5 ](http://wiki.geojson.org/GeoJSON_draft_version_5)

CRS Examples
```
"crs": {
      "type": "EPSG",
      "properties": { 
         "code": 4326,
         "coordinate_order": [1, 0]
      }
    }
```
```
"crs": {
     "type": "URL",
     "properties": { 
        "url": "http://spatialreference.org/ref/epsg/2001/proj4/",
        "type": "proj4"
     }
   }
```

**Comment by maesenka** [comment]
I made some changes to my e-mail filters that had unintended consequences, so I only now noticed your messages. Sorry about that.

I don't intend to support all and every geojson variant, there are just too many of them. But I will put this request on the backlog, since it looks like a small change.

**Comment by billtian** [comment]
@maesenka  thanks a lot !
would crs serialize support be added this time ? #83

**Comment by maesenka** [comment]
Won't fix, since GeoJson draft 5 status is unclear.
